language: python
python:
  - "3.5"
install:
  - pip install -e .
  - pip install mock>=1.3.0
  - pip install pip>=8.1.1
  - pip install pytest>=2.9.1
  - pip install python-coveralls>=2.7.0
  - pip install pytest-cov>=2.2.1
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi"
script: "if [[ $TEST_PEP8 == '1' ]]; then pep8 --max-line-length=100 --ignore E128,E261,E301,E302,E309,E501 --repeat --show-source --exclude=.tox,dist,docs,build,*.egg .; else py.test --cov noscrapy --cov-report=term-missing; fi"
matrix:
  include:
    - python: "3.5"
      env: TEST_PEP8=1
after_success:
  if [[ $TEST_PEP8 != '1' ]]; then coveralls; fi
